# Generated by Django 5.2.1 on 2025-05-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobhub.login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
